server:
  port: 8083
spring:
  application:
    name: =STOCKEXCHANGE-WS
  datasource:
    password: root
    url: jdbc:h2:mem:testdb
    username: root
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    org.springframework.web: DEBUG